# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Othello Development Blog
description: Team 4's development blog for the production of a video game version of Othello.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


team:
  - name: John Berg
    role: System Design, Unit Tester, Graphics Designer
  - name: Arvinder Chatha
    role: System Design
  - name: Zakeria Hirsi
    role: Graphical User Interface & Visual Design, Graphics Designer
  - name: Aleksander Kozina
    role:
  - name: Eastwood Nketiah
    role: Music Design, Web Development, Video Editor
  - name: Sailesh Patel
    role: User Tester, Web Development, Git Flow Monitor
  - name: James Shorthouse
    role: Graphical User Interface & Visual Design, System Administrator, Graphics Designer
  - name: Bruno Simao Zorima
    role: User Tester, Graphics Designer, Web Development, Video Editor
  - name: Charles Sims
    role: Git Flow Monitor

# Build settings
sass:
  sass_dir: css
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
