# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Othello Development Blog
description: Team 4's development blog for the production of a video game version of Othello.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


team:
  - name: John Berg
    roles:
      - role1: System Design
      - role2: Unit Tester
      - role3: Graphics Designer
  - name: Arvinder Chatha
    roles:
      - role1: System Design
  - name: Zakeria Hirsi
    roles:
      - role1: Graphical User Interface Programmer
      - role2: Graphics Designer
  - name: Aleksander Kozina
    roles:
      - role1: Artificial Intelligence
  - name: Eastwood Nketiah
    roles:
      - role1: Music Design
      - role2: Web Development
      - role3: Video Editor
  - name: Sailesh Patel
    roles:
      - role1: User Tester
      - role2: Web Development
      - role3: Git Flow Monitor
  - name: James Shorthouse
    roles:
      - role1: Graphical User Interface Programmer
      - role2: Server Administrator
      - role3: Graphics Designer
  - name: Bruno Simao Zorima
    roles:
      - role1: User Tester
      - role2: Graphics Designer
      - role3: Web Development
      - role4: Video Editor
  - name: Charles Sims
    roles:
      - role1: Git Flow Monitor

# Build settings
sass:
  sass_dir: css
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
